apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: redis-serviceentry
spec:
  hosts:
  - REDIS_ENDPOINT
  ports:
  - number: 6379
    name: tcp-redis
    protocol: TCP
  location: MESH_EXTERNAL
